### ISSUE TITLE
Add possibility to finish match before max score

### ISSUE THREAD

**Issue by lshako** [matco/badminton#21]
Is it possible to finish match immediately (no matter of score)? We have court for 1-2 hours and stop playing when time is gone.

**Comment by matco** [comment]
In the current version, the only thing you can do is to exit the app. This will discard the match and it will not be uploaded to Garmin Connect. I have a pending branch that adds a button in the contextual menu to end a match any time (a part of a bigger try to store/resume later a match).

If I add the "End match" button in the contextual menu, what should happen? Should we upload the match to Garmin Connect? Should we give the user the choice to save or not the match in Garmin Connect? If the match is saved, maybe we should add a flag in the Garmin Connect activity to show that the match is incomplete. What do you think?

**Comment by lshako** [comment]
I think exit from app = exit without saving, so if I want to save it I'll use "End match" button. 
Or it can be like other settings - default settings + possibility to change.  But this one looks like unnecessary complexity. Do you agree?

**Comment by matco** [comment]
I don't think it's a good idea to add too many settings.

I just pushed f4fbfd74d2796a9a9e713b8bff9921f9b9fcda63 that replaces the "exit" entry from the menu by a "end" button. When selected, a confirmation dialog allows to save or discard the match. It's the same confirmation dialog that the one that pops when a match is finished.

I'll see if I add a flag in the Garmin Connect activity to show that the match is incomplete.
