### ISSUE TITLE
Matbe petanque fork?

### ISSUE THREAD

**Issue by yel3n** [matco/badminton#27]
I like your app a lot. I'm a petanque player and i could use it to count score when playing petanque. Maybe you are interested realeasing this type of app?

**Comment by yel3n** [comment]
Ok, I've read the answer for table tennis fork, probably i will try to fork it myself and adapt for my needs

**Comment by matco** [comment]
Hello!

Yeah, even if I recently spent some time working on the app, my opinion stays the same as what I described in #22. Thanks for your message anyway!
