### ISSUE TITLE
Associate match to a Garmin activity

### ISSUE THREAD

**Issue by matco** [matco/badminton#5]
For the moment, it is possible to:
- record heart rate
- record steps count
- rely on activity to store match duration

If Garmin allows custom data in activity, it will also be possible to store:
- final score of matches
- number or rallies

**Comment by haraldh** [comment]
"number or rallies" can be counted with addLap(). Although of course, if someone presses "back" then it's one lap too much.

**Comment by Dominoo** [comment]
Hi are you working on this ? I would love to create activities from this app. I could help you

**Comment by matco** [comment]
More or less. I am stuck because there is a bug in the Garmin SDK. I reported the issue here: [https://forums.garmin.com/showthread.php?359335-Type-of-sport-in-activity-recording-session](https://forums.garmin.com/showthread.php?359335-Type-of-sport-in-activity-recording-session).

As you can see, I am still waiting for an answer from the Garmin Connect IQ team. While this bug is not fixed, activities sent by the app are useless.

**Comment by matco** [comment]
Done in v2.0.0.
